### ISSUE TITLE
1.17.1 Could not find required Mod

### ISSUE THREAD

**Issue by WannaGrenade** [yungnickyoung/YUNGs-Better-Dungeons#15]
Not an issue, I'm just reporting that you don't specify you need the Cloth Config API (Fabric) to load your mods. Your page only reports it needs your API. 

> Currently, YUNG's API (Fabric) is only required for the following mods:

C:\Users\-----\Desktop\Fabric Server>java -jar fabric-server-launch.jar
[14:14:22] [main/INFO]: Loading for game Minecraft 1.17.1
[14:14:23] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: betterdungeons requires {cloth-config2 @ [>=5.0.0]}
        at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
        at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195) ~[fabric-server-launch.jar:?]
        ... 12 more

**Comment by yungnickyoung** [comment]
Which file? It looks like it's marked as required here: https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons-fabric/files/3455978

**Comment by WannaGrenade** [comment]
On the main page. When you have the fancy image link for dependency for your API. 

Again, its not a big issue, but often when people go to the download the mod, they use the download button which brings the user to a page that does not list all dependencies unlike the files page. I was confused at first since cloth API was not stated on the mod description page.

**Comment by yungnickyoung** [comment]
Almost every mod on CF does not specify dependencies in the post. That's the point of the dependencies tab.
