### ISSUE TITLE
[1.18.1 -> 1.18.2] "Couldn't load chunk. Unknown structure." resulting in new chunk generation.

### ISSUE THREAD

**Issue by paulhlschr** [yungnickyoung/YUNGs-Better-Dungeons#33]
## Description
Harsh chunk borders generate while console/log of the server is bloated by the following.
The map was originally generated on Minecraft 1.18.1 using Better Dungeons 1.18.1-1.0.1.
```
[03May2022 13:56:28.305] [Server thread/ERROR] [net.minecraft.server.level.ChunkMap/]: Couldn't load chunk [-139, 114]
java.lang.IllegalStateException: Found unknown structure: betterdungeons:small_dungeon
	at net.minecraft.util.datafix.fixes.StructuresBecomeConfiguredFix.m_207723_(StructuresBecomeConfiguredFix.java:188) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.util.datafix.fixes.StructuresBecomeConfiguredFix.m_207687_(StructuresBecomeConfiguredFix.java:181) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at com.mojang.datafixers.util.Pair.mapFirst(Pair.java:64) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at net.minecraft.util.datafix.fixes.StructuresBecomeConfiguredFix.m_207710_(StructuresBecomeConfiguredFix.java:181) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.util.datafix.fixes.StructuresBecomeConfiguredFix.m_207696_(StructuresBecomeConfiguredFix.java:177) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at com.mojang.serialization.Dynamic.lambda$null$4(Dynamic.java:71) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at com.mojang.serialization.Dynamic.lambda$updateMapValues$5(Dynamic.java:73) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.datafixers.util.Either$Left.mapBoth(Either.java:33) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.serialization.DataResult.map(DataResult.java:110) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.serialization.Dynamic.updateMapValues(Dynamic.java:70) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at net.minecraft.util.datafix.fixes.StructuresBecomeConfiguredFix.m_207716_(StructuresBecomeConfiguredFix.java:177) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.util.datafix.fixes.StructuresBecomeConfiguredFix.m_207729_(StructuresBecomeConfiguredFix.java:137) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at com.mojang.serialization.Dynamic.lambda$null$13(Dynamic.java:136) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.serialization.DynamicOps.lambda$update$21(DynamicOps.java:222) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.datafixers.util.Either$Left.mapBoth(Either.java:33) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.serialization.DataResult.map(DataResult.java:110) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.serialization.DynamicOps.update(DynamicOps.java:222) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.serialization.Dynamic.lambda$update$14(Dynamic.java:136) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.serialization.Dynamic.map(Dynamic.java:36) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.serialization.Dynamic.update(Dynamic.java:136) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at net.minecraft.util.datafix.fixes.StructuresBecomeConfiguredFix.m_207726_(StructuresBecomeConfiguredFix.java:137) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at com.mojang.serialization.Dynamic.lambda$null$13(Dynamic.java:136) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.serialization.DynamicOps.lambda$update$21(DynamicOps.java:222) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.datafixers.util.Either$Left.mapBoth(Either.java:33) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.serialization.DataResult.map(DataResult.java:110) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.serialization.DynamicOps.update(DynamicOps.java:222) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.serialization.Dynamic.lambda$update$14(Dynamic.java:136) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.serialization.Dynamic.map(Dynamic.java:36) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.serialization.Dynamic.update(Dynamic.java:136) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at net.minecraft.util.datafix.fixes.StructuresBecomeConfiguredFix.m_207691_(StructuresBecomeConfiguredFix.java:134) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at com.mojang.datafixers.DataFix.lambda$null$1(DataFix.java:51) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.datafixers.functions.Comp.lambda$null$5(Comp.java:69) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.datafixers.types.Type.capWrite(Type.java:167) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.datafixers.types.Type.lambda$readAndWrite$9(Type.java:159) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.datafixers.types.Type.readAndWrite(Type.java:158) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.datafixers.DataFixerUpper.update(DataFixerUpper.java:84) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at net.minecraft.nbt.NbtUtils.m_129218_(NbtUtils.java:488) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.nbt.NbtUtils.m_129213_(NbtUtils.java:484) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.world.level.chunk.storage.ChunkStorage.m_188288_(ChunkStorage.java:54) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.level.ChunkMap.m_140427_(ChunkMap.java:902) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.level.ChunkMap.m_203107_(ChunkMap.java:539) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:532) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:540) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:266) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:787) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:761) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

## Specifications
Minecraft 1.18.2
Forge 40.1.0
on a server-environment

## Log Files
[debug.log](https://gist.github.com/paulhlschr/ebcd2e084276babd4371a39dd35bbac9#file-debug-log)
[latest.log](https://gist.github.com/paulhlschr/ebcd2e084276babd4371a39dd35bbac9#file-latest-log)

## Screenshot
![2022-05-03_14 09 02](https://user-images.githubusercontent.com/20583201/166450082-d612ee3a-daae-4d31-8676-ee8afa200327.png)

## Modlist
[Actually Compatible](https://www.curseforge.com/projects/550269)
[AI Improvements](https://www.curseforge.com/projects/233019)
[AIOT Botania](https://www.curseforge.com/projects/294815)
[Akashic Tome](https://www.curseforge.com/projects/250577)
[Alex's Mobs](https://www.curseforge.com/projects/426558)
[Apotheosis](https://www.curseforge.com/projects/313970)
[AppleSkin](https://www.curseforge.com/projects/248787)
[Ars Nouveau](https://www.curseforge.com/projects/401955)
[AttributeFix](https://www.curseforge.com/projects/280510)
[AutoRegLib](https://www.curseforge.com/projects/250363)
[Balm (Forge Edition)](https://www.curseforge.com/projects/531761)
[Bookshelf](https://www.curseforge.com/projects/228525)
[Botania](https://www.curseforge.com/projects/225643)
[Caelus API (Forge)](https://www.curseforge.com/projects/308989)
[Carry On](https://www.curseforge.com/projects/274259)
[Catalogue](https://www.curseforge.com/projects/459701)
[Chisels & Bits - For Forge](https://www.curseforge.com/projects/231095)
[Citadel](https://www.curseforge.com/projects/331936)
[Cloth Config API (Forge)](https://www.curseforge.com/projects/348521)
[Clumps](https://www.curseforge.com/projects/256717)
[CobbleGenRandomizer](https://www.curseforge.com/projects/402256)
[Compost](https://www.curseforge.com/projects/581323)
[Configured](https://www.curseforge.com/projects/457570)
[Corpse](https://www.curseforge.com/projects/316582)
[Cosmetic Armor Reworked](https://www.curseforge.com/projects/237307)
[Crafting Tweaks](https://www.curseforge.com/projects/233071)
[Create Confectionery](https://www.curseforge.com/projects/531834)
[Create Deco](https://www.curseforge.com/projects/509285)
[Create Stuff Additions](https://www.curseforge.com/projects/466792)
[Create](https://www.curseforge.com/projects/328085)
[Create Crafts & Additions](https://www.curseforge.com/projects/439890)
[Culinary Construct](https://www.curseforge.com/projects/296676)
[Curio of Undying (Forge)](https://www.curseforge.com/projects/316873)
[Curios API (Forge)](https://www.curseforge.com/projects/309927)
[Curious Elytra (Forge)](https://www.curseforge.com/projects/317716)
[Debugify](https://www.curseforge.com/projects/596224)
[Decorative Blocks](https://www.curseforge.com/projects/362528)
[Diet (Forge)](https://www.curseforge.com/projects/443570)
[Duckling](https://www.curseforge.com/projects/597248)
[Dynamic View[Forge/Fabric]](https://www.curseforge.com/projects/366140)
[Ecologics](https://www.curseforge.com/projects/570463)
[Enchantment Descriptions](https://www.curseforge.com/projects/250419)
[Engineer's Decor](https://www.curseforge.com/projects/313866)
[Entity Culling Fabric/Forge](https://www.curseforge.com/projects/448233)
[Farmer's Delight](https://www.curseforge.com/projects/398521)
[Farsight [Forge]](https://www.curseforge.com/projects/495693)
[FastFurnace](https://www.curseforge.com/projects/299540)
[FastSuite](https://www.curseforge.com/projects/475117)
[FastWorkbench](https://www.curseforge.com/projects/288885)
[FerriteCore (Forge)](https://www.curseforge.com/projects/429235)
[Flywheel](https://www.curseforge.com/projects/486392)
[Forbidden and Arcanus](https://www.curseforge.com/projects/309858)
[GeckoLib](https://www.curseforge.com/projects/388172)
[Hexerei](https://www.curseforge.com/projects/548599)
[Immersive Engineering](https://www.curseforge.com/projects/231951)
[Incendium](https://www.curseforge.com/projects/591388)
[Jade Addons](https://www.curseforge.com/projects/583345)
[Jade 🔍](https://www.curseforge.com/projects/324717)
[Just Enough Items (JEI)](https://www.curseforge.com/projects/238222)
[JER Integration](https://www.curseforge.com/projects/506948)
[Just Enough Effect Descriptions (JEED)](https://www.curseforge.com/projects/532286)
[Just Enough Professions (JEP)](https://www.curseforge.com/projects/417645)
[Just Enough Resources (JER)](https://www.curseforge.com/projects/240630)
[Little Logistics](https://www.curseforge.com/projects/570050)
[Lootr (Forge)](https://www.curseforge.com/projects/361276)
[Macaw's Bridges](https://www.curseforge.com/projects/351725)
[Macaw's Doors](https://www.curseforge.com/projects/378646)
[Macaw's Fences and Walls](https://www.curseforge.com/projects/453925)
[Macaw's Furniture](https://www.curseforge.com/projects/359540)
[Macaw's Lights and Lamps](https://www.curseforge.com/projects/502372)
[Macaw's Paintings](https://www.curseforge.com/projects/438116)
[Macaw's Roofs](https://www.curseforge.com/projects/352039)
[Macaw's Trapdoors](https://www.curseforge.com/projects/400933)
[Macaw's Windows](https://www.curseforge.com/projects/363569)
[Mod Name Tooltip](https://www.curseforge.com/projects/238747)
[Mouse Tweaks](https://www.curseforge.com/projects/60089)
[Nether's Delight](https://www.curseforge.com/projects/496394)
[Not Enough Animations](https://www.curseforge.com/projects/433760)
[Not Enough Crashes (Forge)](https://www.curseforge.com/projects/442354)
[Pam's HarvestCraft 2 - Food Core](https://www.curseforge.com/projects/372534)
[Patchouli](https://www.curseforge.com/projects/306770)
[Pettable Bees (Forge)](https://www.curseforge.com/projects/535485)
[Placebo](https://www.curseforge.com/projects/283644)
[Plasmo Voice](https://www.curseforge.com/projects/467028)
[Regrowth](https://www.curseforge.com/projects/381597)
[Selene Lib](https://www.curseforge.com/projects/499980)
[Shutup Experimental Settings!](https://www.curseforge.com/projects/407174)
[Skin Layers 3D (Fabric/Forge)](https://www.curseforge.com/projects/521480)
[Smooth Chunk Save](https://www.curseforge.com/projects/582327)
[Sophisticated Backpacks](https://www.curseforge.com/projects/422301)
[Sophisticated Core](https://www.curseforge.com/projects/618298)
[Sound Physics Remastered](https://www.curseforge.com/projects/535489)
[Storage Drawers](https://www.curseforge.com/projects/223852)
[Supplementaries](https://www.curseforge.com/projects/412082)
[Terralith](https://www.curseforge.com/projects/513688)
[Valhelsia Core](https://www.curseforge.com/projects/416935)
[Water Strainer](https://www.curseforge.com/projects/246939)
[YUNG's API (Forge)](https://www.curseforge.com/projects/421850)
[YUNG's Better Dungeons (Forge)](https://www.curseforge.com/projects/510089)
[YUNG's Better Mineshafts (Forge)](https://www.curseforge.com/projects/389665)
[YUNG's Better Strongholds (Forge)](https://www.curseforge.com/projects/465575)

**Comment by paulhlschr** [comment]
To add to this, I made screenshots from the old environment. The existence of the spider cave breaks the chunk when upgrading the world to 1.18.2.

![2022-05-03_14 22 00](https://user-images.githubusercontent.com/20583201/166452211-24418b87-0cd5-4f66-b352-1f3717ff3f6a.png)
![2022-05-03_14 22 42](https://user-images.githubusercontent.com/20583201/166452215-2ee117c7-c27a-4a43-9d64-74200e77155f.png)
![2022-05-03_14 22 57](https://user-images.githubusercontent.com/20583201/166452224-3b94c54f-0a31-4ce9-9272-48d37001bf95.png)

**Comment by yungnickyoung** [comment]
I'm not sure why this happened; the structure names didn't change from 1.18.1 to 1.18.2. 1.18.2 did introduce some major changes in the way structures work and need to be registered, so perhaps I needed to add a DFU to allow players to update their worlds - but that's just speculation.

Gonna be marking this as won't fix. While ensuring worlds can always update to new versions is a big priority for Mojang, I unfortunately don't have the time to provide that guarantee. Sorry about that.
