### ISSUE TITLE
Crashing on 1.20.1

### ISSUE THREAD

**Issue by iustin94** [yungnickyoung/YUNGs-Better-Dungeons#67]
I been having issues with running all the YUNG mods. As it turns out 4 mods in particular cause the following error log. The mods in question are Better Dungeons, Bridges, Extras, and Menu Tweaks. Something in these breaks the game.

```
---- Minecraft Crash Report ----
// Ooh. Shiny.
Time: 2024-07-30 22:01:50
Description: mouseClicked event handler
java.lang.IllegalStateException: Failed to load registries due to above errors
at net.minecraft.class_7655.method_45121(class_7655.java:111)
at net.minecraft.class_7237.method_45142(class_7237.java:67)
at net.minecraft.class_7237.method_45143(class_7237.java:71)
at net.minecraft.class_7237.method_42098(class_7237.java:34)
at net.minecraft.class_525.method_31130(class_525.java:333)
at net.minecraft.class_528.method_43462(class_528.java:169)
at net.minecraft.class_528.<init>(class_528.java:95)
at net.minecraft.class_526.method_25426(class_526.java:54)
at net.minecraft.class_437.method_25423(class_437.java:297)
at net.minecraft.class_310.method_1507(class_310.java:1080)
at net.minecraft.class_442.method_19861(class_442.java:159)
at net.minecraft.class_4185.method_25306(class_4185.java:94)
at net.minecraft.class_4264.method_25348(class_4264.java:56)
at net.minecraft.class_339.method_25402(class_339.java:189)
at net.minecraft.class_4069.method_25402(class_4069.java:38)
at net.minecraft.class_442.method_25402(class_442.java:299)
at net.minecraft.class_312.method_1611(class_312.java:98)
at net.minecraft.class_437.method_25412(class_437.java:409)
at net.minecraft.class_312.method_1601(class_312.java:98)
at net.minecraft.class_312.method_22686(class_312.java:169)
at net.minecraft.class_1255.execute(class_1255.java:102)
at net.minecraft.class_312.method_22684(class_312.java:169)
at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
at org.lwjgl.system.JNI.invokeV(Native Method)
at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
at net.minecraft.class_310.method_1523(class_310.java:1244)
at net.minecraft.class_310.method_1514(class_310.java:802)
at net.minecraft.client.main.Main.main(Main.java:250)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
at net.minecraft.class_7655.method_45121(class_7655.java:111)
at net.minecraft.class_7237.method_45142(class_7237.java:67)
at net.minecraft.class_7237.method_45143(class_7237.java:71)
at net.minecraft.class_7237.method_42098(class_7237.java:34)
at net.minecraft.class_525.method_31130(class_525.java:333)
at net.minecraft.class_528.method_43462(class_528.java:169)
at net.minecraft.class_528.<init>(class_528.java:95)
at net.minecraft.class_526.method_25426(class_526.java:54)
at net.minecraft.class_437.method_25423(class_437.java:297)
at net.minecraft.class_310.method_1507(class_310.java:1080)
at net.minecraft.class_442.method_19861(class_442.java:159)
at net.minecraft.class_4185.method_25306(class_4185.java:94)
at net.minecraft.class_4264.method_25348(class_4264.java:56)
at net.minecraft.class_339.method_25402(class_339.java:189)
at net.minecraft.class_4069.method_25402(class_4069.java:38)
at net.minecraft.class_442.method_25402(class_442.java:299)
at net.minecraft.class_312.method_1611(class_312.java:98)
at net.minecraft.class_437.method_25412(class_437.java:409)
at net.minecraft.class_312.method_1601(class_312.java:98)
at net.minecraft.class_312.method_22686(class_312.java:169)
at net.minecraft.class_1255.execute(class_1255.java:102)
at net.minecraft.class_312.method_22684(class_312.java:169)
at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
at org.lwjgl.system.JNI.invokeV(Native Method)
at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
-- Affected screen --
Details:
Screen name: net.minecraft.class_442
Stacktrace:
at net.minecraft.class_437.method_25412(class_437.java:409)
at net.minecraft.class_312.method_1601(class_312.java:98)
at net.minecraft.class_312.method_22686(class_312.java:169)
at net.minecraft.class_1255.execute(class_1255.java:102)
at net.minecraft.class_312.method_22684(class_312.java:169)
at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
at org.lwjgl.system.JNI.invokeV(Native Method)
at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
at net.minecraft.class_310.method_1523(class_310.java:1244)
at net.minecraft.class_310.method_1514(class_310.java:802)
at net.minecraft.client.main.Main.main(Main.java:250)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
-- Last reload --
Details:
Reload number: 1
Reload reason: initial
Finished: Yes
Packs: vanilla, fabric
Stacktrace:
at net.minecraft.class_6360.method_36565(class_6360.java:49)
at net.minecraft.class_310.method_1587(class_310.java:2413)
at net.minecraft.class_310.method_1514(class_310.java:821)
at net.minecraft.client.main.Main.main(Main.java:250)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
-- System Details --
Details:
Minecraft Version: 1.20.1
Minecraft Version ID: 1.20.1
Operating System: Linux (amd64) version 6.5.0-45-generic
Java Version: 17.0.8, Microsoft
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
Memory: 218094656 bytes (207 MiB) / 570425344 bytes (544 MiB) up to 4294967296 bytes (4096 MiB)
CPUs: 12
Processor Vendor: AuthenticAMD
Processor Name: AMD Ryzen 5 5600X 6-Core Processor
Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
Microarchitecture: Zen 3
Frequency (GHz): 4.65
Number of physical packages: 1
Number of physical CPUs: 6
Number of logical CPUs: 12
Graphics card #0 name: GA104 [GeForce RTX 3060 Ti]
Graphics card #0 vendor: NVIDIA Corporation (0x10de)
Graphics card #0 VRAM (MB): 288.00
Graphics card #0 deviceId: 0x2486
Graphics card #0 versionInfo: unknown
Virtual memory max (MB): 9999.86
Virtual memory used (MB): 6782.00
Swap memory total (MB): 2048.00
Swap memory used (MB): 0.25
JVM Flags: 3 total; -Xss1M -Xmx4096m -Xms256m
Fabric Mods: 
 ambientsounds: AmbientSounds 6.0.3
 antique-atlas: Antique Atlas 2.9.12+1.20
  surveyor: Surveyor Map Framework 0.6.11+1.20
   folk_sisby_kaleido-config: kaleido-config 0.3.1+1.3.1
 badpackets: Bad Packets 0.4.3
 bcc: BetterCompatibilityChecker 4.0.8
 betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
  org_reflections_reflections: reflections 0.10.2
 betterendisland: YUNG's Better End Island 1.20-Fabric-2.0.6
 betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.6
 betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.5
 bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
 betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
 betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
 betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
 cameraoverhaul: Camera Overhaul 1.4.1-fabric-universal
 cloth-config: Cloth Config v11 11.1.118
  cloth-basic-math: cloth-basic-math 0.6.1
 creativecore: CreativeCore 2.11.33
  net_minecraftforge_eventbus: eventbus 6.0.3
 cupboard: cupboard 1.20.1-2.7
 distanthorizons: Distant Horizons 2.1.2-a
 fabric-api: Fabric API 0.92.2+1.20.1
  fabric-api-base: Fabric API Base 0.4.31+1802ada577
  fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
  fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
  fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
  fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
  fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
  fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
  fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
  fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
  fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
  fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
  fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
  fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
  fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
  fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
  fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
  fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
  fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
  fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
  fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
  fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
  fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
  fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
  fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
  fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
  fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
  fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
  fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
  fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
  fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
  fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
  fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
  fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
  fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
  fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
  fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
  fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
  fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
  fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
  fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
  fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
  fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
  fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
  fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
  fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
  fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
  fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
  fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
  fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
  fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
  fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
  fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
 fabricloader: Fabric Loader 0.15.11
  mixinextras: MixinExtras 0.3.5
 firstperson: FirstPerson 2.4.4
 geophilic: Geophilic 3.1.0
 indium: Indium 1.0.34+mc1.20.1
 iris: Iris 1.7.2+mc1.20.1
  io_github_douira_glsl-transformer: glsl-transformer 2.0.1
  org_anarres_jcpp: jcpp 1.4.14
  org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
 java: OpenJDK 64-Bit Server VM 17
 jei: Just Enough Items 15.8.2.25
 lootintegrationaddonyung: Yung's Structures Lootintegration Addon 1.18-1.20.1-1.1
 lootintegrations: Loot integration Mod 1.20.1-3.7
 minecraft: Minecraft 1.20.1
 modmenu: Mod Menu 7.2.2
 reterraforged: ReTerraForged 0.0.5
 sodium: Sodium 0.5.11+mc1.20.1
 wthit: wthit 8.13.3
 yungsapi: YUNG's API 1.20-Fabric-4.0.5
  org_javassist_javassist: javassist 3.29.2-GA
 yungsbridges: YUNG's Bridges 1.20-Fabric-4.0.3
 yungsextras: YUNG's Extras 1.20-Fabric-4.0.3
 yungsmenutweaks: YUNG's Menu Tweaks 1.20.1-Fabric-1.0.2
Loaded Shaderpack: (off)
Launched Version: fabric-loader-0.15.11-1.20.1
Backend library: LWJGL version 3.3.1 SNAPSHOT
Backend API: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 535.183.01, NVIDIA Corporation
Window size: 1024x768
GL Caps: Using framebuffer using OpenGL 3.2
GL debug messages: 
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fabric'
Type: Client (map_client.txt)
Graphics mode: fancy
Resource Packs: fabric
Current Language: en_us
CPU: 12x AMD Ryzen 5 5600X 6-Core Processor
```

**Comment by imeesa** [comment]
Do you have Incendium installed?

**Comment by iustin94** [comment]
No, i do have Indium though, in case they are related?

**Comment by imeesa** [comment]
Nope, completely seperate mods.
